## Reading data From different sources

In [3]:
import pandas as pd
from io import StringIO
Data ='{"employee_id": [1, 2, 3, 4, 5], "employee_name": ["John", "Jane", "Doe", "Smith", "Emily"], "department": ["HR", "Finance", "IT", "Marketing", "Sales"]}'
df = pd.read_json(StringIO(Data))
print(df)

   employee_id employee_name department
0            1          John         HR
1            2          Jane    Finance
2            3           Doe         IT
3            4         Smith  Marketing
4            5         Emily      Sales

In [4]:
df.to_json()

'{"employee_id":{"0":1,"1":2,"2":3,"3":4,"4":5},"employee_name":{"0":"John","1":"Jane","2":"Doe","3":"Smith","4":"Emily"},"department":{"0":"HR","1":"Finance","2":"IT","3":"Marketing","4":"Sales"}}'

In [6]:
df.head()

   employee_id employee_name department
0            1          John         HR
1            2          Jane    Finance
2            3           Doe         IT
3            4         Smith  Marketing
4            5         Emily      Sales

In [7]:
df.to_json(orient='records')

'[{"employee_id":1,"employee_name":"John","department":"HR"},{"employee_id":2,"employee_name":"Jane","department":"Finance"},{"employee_id":3,"employee_name":"Doe","department":"IT"},{"employee_id":4,"employee_name":"Smith","department":"Marketing"},{"employee_id":5,"employee_name":"Emily","department":"Sales"}]'

In [8]:
df.to_json(orient='index')

'{"0":{"employee_id":1,"employee_name":"John","department":"HR"},"1":{"employee_id":2,"employee_name":"Jane","department":"Finance"},"2":{"employee_id":3,"employee_name":"Doe","department":"IT"},"3":{"employee_id":4,"employee_name":"Smith","department":"Marketing"},"4":{"employee_id":5,"employee_name":"Emily","department":"Sales"}}'

In [12]:
df=pd.read_csv("dataa.csv")

In [14]:
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [15]:
df.to_csv("new.csv")

In [18]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.0.2-cp312-cp312-win_amd64.whl.metadata (3.7 kB)
Downloading lxml-6.0.2-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.0 MB 6.7 MB/s eta 0:00:01
   ------------------ --------------------- 1.8/4.0 MB 5.9 MB/s eta 0:00:01
   ------------------------------- -------- 3.1/4.0 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 5.1 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.2

In [21]:
url="https://www.hdfc.bank.in/fixed-deposit/fd-interest-rate"
pd.read_html(url)
pd.read_html(url)[0]

,Tenor Bucket,< ₹3 Crore,Unnamed: 2
0,NaN,Interest Rate (per annum),**Senior Citizen Rates (per annum)
1,7 - 14 days,2.75%,3.25%
2,15-29 days,2.75%,3.25%
3,30-45 days,3.25%,3.75%
4,46-60 days,4.25%,4.75%
5,61-89 days,4.25%,4.75%
6,90 days <= 6 months,4.25%,4.75%
7,6 months 1 day <=9 months,5.50%,6.00%
8,9 months 1 day to < 1 Year,5.75%,6.25%
9,1 Year to < 15 months,6.25%,6.75%
10,15 months to < 18 months,6.35%,6.85%
11,18 months to < 21 months,6.45%,6.95%
12,21 months to 2 years,6.45%,6.95%
13,2 Years 1 day to < 2 Year 11 Months,6.45%,6.95%
14,2 Years 11 Months (35 months),6.45%,6.95%
15,2 Years 11 Months 1 day <= 3 Year,6.45%,6.95%
16,3 Years 1 day to < 4 Years 7 Months,6.40%,6.90%
17,4 Year 7 Months (55 months),6.40%,6.90%
18,4 Year 7 Months 1 day <=5 Years,6.40%,6.90%
19,5 Years 1 day to 10 Years,6.15%,6.65%

In [31]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [46]:
df_excel= pd.read_excel(r"C:\Users\HP\Downloads\TechCode.xlsx")
print(df)

      Issue ID First Name Last Name     ATM ID  \
0   0d5ff8ed8d   Fredrick  Thompson      33562
1   d9c1547599      Patsy   Sheehan      66722
2   e0cb653f42        Jon      Snow       3351
3   94803beda8  Alexander     Ramos      37490
4   da18217bc3      Verna     Moore      77827
5   d146f1ccc1      Megan   Iverson      51428
6   045dbe3b7b       Paul     Edson      16252
7   d9d1df320a   Danielle      West      98308
8     JTXhApOb  Alexander     Ramos      37490
9     23a5558b      quick       lab     ABC123
10    ac7aa33f     Freeda       NaN  Freeda123

                                   Email                       Symptom  Photo  \
0    fredrick.thompson@fakeitcompany.com              ATM wont turn on    NaN
1        patsy.sheehan@fakeitcompany.com       Card reader not working    NaN
2             jon.snow@fakeitcompany.com                 Broken keypad    NaN
3      alexander.ramos@fakeitcompany.com               Low cash supply    NaN
4          verna.moore@fakeitcompany.com            Cash dispenser jam    NaN
5        megan.iverson@fakeitcompany.com              Connection error    NaN
6           paul.edson@fakeitcompany.com                    Not listed    NaN
7        danielle.west@fakeitcompany.com  Receipt printer out of paper    NaN
8      alexander.ramos@fakeitcompany.com    Receipt printer out of ink    NaN
9   student-01-41527e028127@qwiklabs.net       Card reader not working    NaN
10                                   NaN    Receipt printer out of ink    NaN

                                         Description          Category  \
0                                ATM screen is black    General Issues
1                   The ATM is not recognizing cards    General Issues
2                  The 2 on the keypad isn't working    General Issues
3   ATM dispensed 2 $10 bills, instead of 1 $20 bill    Cash Dispenser
4                                      Cash is stuck    Cash Dispenser
5                   Cannot connect to bank's network  Connection error
6               ATM is not recognizing a correct PIN    General Issues
7                               Receipt didn't print          Receipts
8                              Receipt printed blank          Receipts
9                                                NaN    General Issues
10                                               NaN          Receipts

     Assigned Tech        Date Created  Resolved  Notes  Date Resolved
0   Shelley Ginder 2016-10-13 18:06:00      True    NaN            NaN
1    Justin Sample 2016-10-14 18:06:00      True    NaN            NaN
2   Shelley Ginder 2016-10-15 18:06:00      True    NaN            NaN
3     Miles Barron 2016-10-16 18:06:00      True    NaN            NaN
4     Miles Barron 2016-10-17 18:06:00     False    NaN            NaN
5        Nia Jones 2016-10-18 18:06:00     False    NaN            NaN
6    Justin Sample 2016-10-19 18:06:00     False    NaN            NaN
7       Jean Clark 2016-10-20 18:06:00     False    NaN            NaN
8       Jean Clark 2016-10-21 18:06:00     False    NaN            NaN
9   Shelley Ginder 2023-07-29 22:37:00     False    NaN            NaN
10      Jean Clark 2023-07-29 22:42:00     False    NaN            NaN

In [49]:
# Save the dataframe to a pickle file


# Load it back if needed
df_excel = pd.read_pickle('df_excel.pkl')

FileNotFoundError: [Errno 2] No such file or directory: 'df_excel.pkl'